substitutions:
  name: kenwood-xs
  friendly_name: Kenwood XS
  ctrl_pin: "4"
  sdat_pin: "5"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

external_components:
  - source: github://gaweueu/KenwoodXS
    components: [kenwood_xs]

logger:

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

kenwood_xs:
  id: kenwood_amp
  ctrl_pin: ${ctrl_pin}
  sdat_pin: ${sdat_pin}
  bidirectional: true
  last_command:
    name: "Kenwood Last Command"
  last_command_code:
    name: "Kenwood Last Command Code"

button:
  - platform: kenwood_xs
    kenwood_xs_id: kenwood_amp
    name: "Kenwood Power On"
    command: POWER_ON

  - platform: kenwood_xs
    kenwood_xs_id: kenwood_amp
    name: "Kenwood Power Off"
    command: POWER_OFF

  - platform: kenwood_xs
    kenwood_xs_id: kenwood_amp
    name: "Kenwood Input CD"
    command: CD

  - platform: kenwood_xs
    kenwood_xs_id: kenwood_amp
    name: "Kenwood Input Tuner"
    command: TUNER

  - platform: kenwood_xs
    kenwood_xs_id: kenwood_amp
    name: "Kenwood CD Play Pause"
    command: CD_PLAY_PAUSE

  - platform: kenwood_xs
    kenwood_xs_id: kenwood_amp
    name: "Kenwood CD Stop"
    command: CD_STOP

  - platform: kenwood_xs
    kenwood_xs_id: kenwood_amp
    name: "Kenwood Raw 181"
    command: 181
